[tool.poetry]
name = "pyzengin"
version = "0.1.3"
description = "Japanese Bank and Branch Code Data"
authors = ["zhengdy@me.com"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
mojimoji = "^0.0.11"
twine = "^3.4.1"

[build-system]
requires = ["setuptools"]
