name: Python Package

on:
  push:
    branches: ["main"]
    tags:
      - "v*.*.*"
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Version bump
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          RELEASE_VERSION: ${{ github.ref_name}}
        run: |
          export version=${RELEASE_VERSION/v/}
          echo "RELEASE_VERSION=$RELEASE_VERSION"
          echo "VERSION=$version"
          sed "s/^version =.*/version = \"$version\"/g" -i pyproject.toml        
      - name: Build and publish to pypi
        if: startsWith(github.ref, 'refs/tags/v')
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          plugins: "poetry-dynamic-versioning"
